@base_url = http://localhost:3333/users

POST {{base_url}}
Content-Type: application/json

{
    "name": "John Doe",
    "email": "felip22322222e@hospitalpaulista.com.br",
    "password": "123456789"
}
